services:
  - type: web
    name: cloudsentinel-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://ep-calm-hall-a1npjp3x-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&user=neondb_owner&password=npg_HZt9NPAcJKv3
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_HZt9NPAcJKv3
      - key: JWT_SECRET
        value: CloudSentinelJWTSecretKey2026ForRender
